version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  search:
    image: elasticsearch:5.6.4
    ports:
      - '127.0.0.1:9200:9200'

  posgis:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=coworker
    ports:
      - "5433:5432"

