version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - es5
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=coworker
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    ports:
      - "5433:5432"
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=coworker

  es5:
    image: elasticsearch:5.6.4
    ports:
      - '127.0.0.1:9200:9200'
