# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170912_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutme',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
    ]
