# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-13 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='profile_image',
        ),
    ]
