# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.TextField(blank=True, null=True, verbose_name='Business name'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_summarize',
            field=models.TextField(blank=True, null=True, verbose_name='Business summarize '),
        ),
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.DateField(blank=True, null=True, verbose_name='Birth day'),
        ),
    ]
