# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170923_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('so', 'Startup Owners'), ('sm', 'Space Map Owners')], default='so', max_length=2),
        ),
    ]
