# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('so', 'Startup Owners'), ('sm', 'Space Owners')], max_length=2, null=True),
        ),
    ]
