# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170923_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sp', 'Spaces'), ('or', 'Organizations'), ('st', 'Startups'), ('in', 'Investors')], max_length=2),
        ),
    ]
