# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_remove_place_user'),
        ('users', '0012_auto_20171118_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
