# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:33
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lng',
        ),
        migrations.AddField(
            model_name='place',
            name='lat_lng',
            field=location_field.models.spatial.LocationField(null=True),
            preserve_default=False,
        ),
    ]
