# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20170914_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Member_Payment',
        ),
        migrations.AddField(
            model_name='place',
            name='accs',
            field=models.BooleanField(default=True, help_text='Do you accept credit cards?'),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='address_sec',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='apps',
            field=models.BooleanField(default=True, help_text='Can members pay with PayPal?'),
        ),
        migrations.AddField(
            model_name='place',
            name='area',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='cityLat',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='cityLng',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='deposit',
            field=models.CharField(default=1, help_text='eg. none, 1 month, etc', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='ls_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='notification_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='opay',
            field=models.BooleanField(default=True, help_text='Can members pay online?'),
        ),
        migrations.AddField(
            model_name='place',
            name='postal_code',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='tel',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tel'),
        ),
        migrations.AddField(
            model_name='place',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='website_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Website'),
        ),
    ]
