# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20171114_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='user/photos'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat_lng',
            field=location_field.models.spatial.LocationField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='ls_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='place',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
