# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20171117_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat_lng',
            field=location_field.models.spatial.LocationField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
