# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20170915_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='member_accs',
            field=models.CharField(choices=[('OH', 'Same as opening hours'), ('24H', '24 hours')], default='OH', max_length=2),
        ),
    ]
