# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_member_accs'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='is_header_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.FileField(default=1, upload_to='user/photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
