# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20171117_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='accs',
        ),
        migrations.RemoveField(
            model_name='place',
            name='apps',
        ),
        migrations.RemoveField(
            model_name='place',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='place',
            name='friday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='friday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='member_accs',
        ),
        migrations.RemoveField(
            model_name='place',
            name='monday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='monday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opay',
        ),
        migrations.RemoveField(
            model_name='place',
            name='saturday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='saturday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sunday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sunday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='thursday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='thursday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tuesday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tuesday_to',
        ),
        migrations.RemoveField(
            model_name='place',
            name='wednesday_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='wednesday_to',
        ),
    ]
