# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20171118_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ot', 'Official team'), ('cm', 'New member'), ('pm', 'Old member')], default='ot', max_length=2, null=True),
        ),
    ]
