# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20170915_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photo',
            new_name='file',
        ),
    ]
