# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0010_auto_20170915_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='place',
        ),
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
