# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_remove_place_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
    ]
