# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_auto_20170915_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
    ]
