# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_auto_20170922_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
            preserve_default=False,
        ),
    ]
