# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_auto_20170923_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
