# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_auto_20170924_2006'),
        ('place', '0017_photos_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.CityOrigin'),
        ),
    ]
