# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0017_photos_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='member_accs',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sat_open',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sun_close',
        ),
    ]
