# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_auto_20170924_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='member_accs',
            field=models.CharField(choices=[('OH', 'Same as opening hours'), ('24H', '24 hours')], default='OH', max_length=3),
        ),
    ]
