# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_auto_20170925_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='file',
            new_name='image',
        ),
    ]
