# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_auto_20170924_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDeskPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1h', '1 hour'), ('1d', '1 hour'), ('1w', '1 week'), ('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months'), ('1y', '1 year')], max_length=4)),
                ('seating_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Membership Desk Price',
                'verbose_name_plural': 'Membership Desk Prices',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='deposit',
            field=models.CharField(blank=True, max_length=250, verbose_name='eg. none, 1 month, etc'),
        ),
        migrations.AddField(
            model_name='membershipdeskprice',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
