# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0022_auto_20170924_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdeskprice',
            name='hot_desks',
            field=models.BooleanField(default=False),
        ),
    ]
