# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0023_membershipdeskprice_hot_desks'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdeskprice',
            name='member_accs',
            field=models.CharField(choices=[('OH', 'Reception Hours'), ('24H', '24 hours')], default='OH', max_length=3),
        ),
    ]
