# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_membershipdeskprice_member_accs'),
        ('place', '0019_place_slug'),
    ]

    operations = [
    ]
