# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_membershipdeskprice_member_accs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOfficePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months'), ('1y', '1 year'), ('18m', '18 months'), ('2y', '2 years')], max_length=4)),
                ('seating_price', models.IntegerField()),
                ('member_accs', models.CharField(choices=[('OH', 'Reception Hours'), ('24H', '24 hours')], default='OH', max_length=3)),
            ],
            options={
                'verbose_name': 'Membership Office Price',
                'verbose_name_plural': 'Membership Office Prices',
            },
        ),
        migrations.CreateModel(
            name='MembershipPrivateOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=250, verbose_name='Name of private office')),
                ('number_of_people', models.PositiveIntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('wboard', models.BooleanField(verbose_name='Does the office have a whiteboard')),
                ('qty', models.PositiveIntegerField(choices=[(0, '0'), (1, '1')], default=0)),
            ],
            options={
                'verbose_name': 'Private office',
                'verbose_name_plural': 'Private offices',
            },
        ),
        migrations.RenameField(
            model_name='membershipdeskprice',
            old_name='hot_desks',
            new_name='hot_desk',
        ),
        migrations.AddField(
            model_name='place',
            name='book_tour',
            field=models.BooleanField(default=True, help_text='Choose the days and times that visitors can book a tour.', verbose_name='Book A Tour'),
        ),
        migrations.AddField(
            model_name='place',
            name='enable_reservation',
            field=models.BooleanField(default=True, help_text="This will allow people to select the membership type they want and start date. You'll receive their reservation request via email so you can follow up with them to confirm and arrange payment.", verbose_name='Enable reservations'),
        ),
        migrations.AddField(
            model_name='place',
            name='free_day_pass',
            field=models.BooleanField(default=True, help_text='Choose the days that visitors can book a free day pass, and the hours they have access.', verbose_name='Get a Free Day Pass'),
        ),
        migrations.AddField(
            model_name='membershipprivateoffice',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AddField(
            model_name='membershipofficeprice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.MembershipPrivateOffice'),
        ),
    ]
