# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0025_auto_20170925_1449'),
        ('place', '0025_merge_20170924_2338'),
    ]

    operations = [
    ]
