# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_auto_20170925_1804'),
        ('place', '0026_merge_20170925_1610'),
    ]

    operations = [
    ]
