# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0028_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='hire_nm',
            field=models.BooleanField(default=False, verbose_name='允许非会员在我的创客云图场地举办大型活动?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='rent_nm',
            field=models.BooleanField(default=False, verbose_name='允许非会员租用我的会议室?'),
        ),
    ]
