# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0031_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Category'),
            preserve_default=False,
        ),
    ]
