# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:45
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lng',
        ),
        migrations.AddField(
            model_name='event',
            name='lat_lng',
            field=location_field.models.spatial.LocationField(),
            preserve_default=False,
        ),
    ]
