# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171103_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
