# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171103_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(default=1, upload_to='events/photos'),
            preserve_default=False,
        ),
    ]
