# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='investors',
            field=models.ManyToManyField(to='events.Investor'),
        ),
    ]
