# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20171107_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='startup/photos')),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
