# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_created=True, db_index=True),
        ),
    ]
