# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20171118_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
