# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('short_name', models.CharField(max_length=40, verbose_name='Short name')),
                ('level_type', models.PositiveIntegerField(choices=[(0, 'China'), (1, 'Province'), (2, 'City'), (3, 'Country')], verbose_name='Level type')),
                ('city_code', models.CharField(max_length=7, verbose_name='City code')),
                ('zip_code', models.CharField(max_length=7, verbose_name='Zip code')),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude')),
                ('lng', models.CharField(max_length=20, verbose_name='Longitude')),
                ('pinyin', models.CharField(max_length=40, verbose_name='Chinese Pinyin')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
            ],
        ),
    ]
