# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20170920_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('city_code', models.CharField(blank=True, max_length=7, verbose_name='City code')),
                ('zip_code', models.CharField(blank=True, max_length=7, verbose_name='Zip code')),
                ('lat', models.CharField(blank=True, max_length=20, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=20, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Contenent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('contenent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Contenent')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('contenent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Country')),
            ],
        ),
    ]
