# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_city_origin_contenent_country_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City_Origin',
            new_name='CityOrigin',
        ),
    ]
