# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20170924_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='contenent',
        ),
        migrations.AddField(
            model_name='cityorigin',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.Country'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
