# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_auto_20170924_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityorigin',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='City image'),
        ),
    ]
