# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_cityorigin_desctiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityorigin',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenent',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
