# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_auto_20170924_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenent',
            name='desctiption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='desctiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
