# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_auto_20170924_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenent',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cityorigin',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
