# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20170924_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityorigin',
            old_name='desctiption',
            new_name='description',
        ),
    ]
