# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20170925_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityorigin',
            name='short_name',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
