# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20171108_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='internal name')),
                ('name', models.CharField(max_length=100, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'service attribute',
                'verbose_name_plural': 'service attributes',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('has_variants', models.BooleanField(default=True, verbose_name='has variants')),
                ('is_shipping_required', models.BooleanField(default=False, verbose_name='is shipping required')),
                ('service_attributes', models.ManyToManyField(blank=True, related_name='service_class', to='services.ServiceAttribute', verbose_name='service attributes')),
                ('variant_attributes', models.ManyToManyField(blank=True, related_name='service_variants_class', to='services.ServiceAttribute', verbose_name='variant attributes')),
            ],
            options={
                'verbose_name': 'Service class',
                'verbose_name_plural': 'Service classes',
            },
        ),
    ]
