# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceattribute_serviceclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceClass',
            new_name='Service',
        ),
    ]
