# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20171108_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceClass',
        ),
    ]
