# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('lab', '0002_auto_20171106_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sites',
            field=models.ManyToManyField(help_text='Sites where the entry will be published.', related_name='entries', to='sites.Site', verbose_name='sites'),
        ),
    ]
