# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 18:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_entry_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='content'),
        ),
    ]
