# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20171107_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='entry',
            name='content_zh_hans',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
